baseURL = "/"
title = "Eko Salvinus"
copyright = "Copyright © Eko Salvinus"
paginate = 2
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
googleAnalytics = "UA-XXXX"
DisqusShortname = ""
theme = "chunky"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 10
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 0
  [[menu.main]]
    identifier = "post"
    name = "Post"
    url = "/post/"
    weight = 0
  [[menu.main]]
    identifier = "portfolio"
    name = "Projects"
    url = "/categories/portfolio/"
    weight = 0

[taxonomies]
category = "categories"
tag = "tags"
series = "series"
author = "authors"

[params]
  author = "Eko Salvinus"
  description = "Website Developer & UI Designer"
  homepageImage = "/images/homepage-image.jpg"
  # dateFormat = "February 2, 2022"
  share = true
  showLanguageSwitcher = false

  # Custom CSS and JS. Relative to /static/css and /static/js respectively.
  customCSS = []
  customJS = []

  [params.social]
    rss = true
    email = "ekosalvinus@gmail.com"
    # facebook = "https://facebook.com"
    twitter = "https://twitter.com/salvinus17"
    linkedin = "https://www.linkedin.com/in/ekosalvinus/"
    # stack-overflow = "https://stackoverflow.com"
    # instagram = "https://stackoverflow.com"
    github = "https://github.com/ekosalvinus"
    # weibo = "https://www.weibo.com"
    medium = "https://ekosalvinus.medium.com/"
    # pinterest = "https://pinterest.com"
    # reddit = "https://reddit.com"
    # gitlab = "https://gitlab.com"
    # mastodon = "https://mastodon.social"
    # keybase = "https://keybase.io/"

  [params.prismJS]
    enable = true
    theme = ""

  [params.commento]
    enable = true
    url = "https://commento.io"

[markup]
  [markup.highlight]
    codeFences = false

[services]
  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true
